//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ARQUIVODETALHE
    {
        public int ID { get; set; }
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "O campo nome é obrigatório!")]
        public string NOME { get; set; }
        [Display(Name = "Descrição")]
        public string DESCRICAO { get; set; }
        [Display(Name = "Arquivo")]
        public int ID_ARQUIVO { get; set; }
        [Display(Name = "Layout")]
        [Range(1, int.MaxValue, ErrorMessage = "O layout do arquivo é obrigatório!")]
        public int ID_LAYOUT { get; set; }
        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> CRIACAO { get; set; }
        [Display(Name = "Data de Alteração")]
        public Nullable<System.DateTime> ALTERACAO { get; set; }
    
        public virtual ARQUIVO ARQUIVO { get; set; }
        public virtual LAYOUT LAYOUT { get; set; }
    }
}
