//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ARQUIVODETALHE
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public int ID_ARQUIVO { get; set; }
        public int ID_LAYOUT { get; set; }
        public Nullable<System.DateTime> CRIACAO { get; set; }
        public Nullable<System.DateTime> ALTERACAO { get; set; }
    
        public virtual ARQUIVO ARQUIVO { get; set; }
        public virtual LAYOUT LAYOUT { get; set; }
    }

    [MetadataType(typeof(ArquivoDetalheMetaData))]
    public partial class ARQUIVODETALHE
    {
        
    }

    public class ArquivoDetalheMetaData
    {
        public int ID { get; set; }
        [Display(Name="Nome")]
        [Required(ErrorMessage="O campo nome é obrigatório!")]
        [StringLength(50)]
        public string NOME { get; set; }
        [Display(Name = "Descrição")]
        [StringLength(200)]
        public string DESCRICAO { get; set; }
        [Display(Name = "Arquivo")]
        [Range(1, Int32.MaxValue, ErrorMessage="O tipo de arquivo é obrigatório!")]
        public int ID_ARQUIVO { get; set; }
        [Display(Name = "Layout")]
        [Range(1, Int32.MaxValue, ErrorMessage = "O layout é obrigatório!")]
        public int ID_LAYOUT { get; set; }
        [Display(Name = "Data de criação")]
        public Nullable<System.DateTime> CRIACAO { get; set; }
        [Display(Name = "Data de alteração")]
        public Nullable<System.DateTime> ALTERACAO { get; set; }

        public virtual ARQUIVO ARQUIVO { get; set; }
        public virtual LAYOUT LAYOUT { get; set; }
    }
}
