//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARQUIVODETALHE
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public int ID_ARQUIVO { get; set; }
        public int ID_LAYOUT { get; set; }
        public Nullable<System.DateTime> CRIACAO { get; set; }
        public Nullable<System.DateTime> ALTERACAO { get; set; }
    
        public virtual ARQUIVO ARQUIVO { get; set; }
        public virtual LAYOUT LAYOUT { get; set; }
    }
}
