//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LAYOUT
    {
        public LAYOUT()
        {
            this.ARQUIVODETALHE = new HashSet<ARQUIVODETALHE>();
        }
    
        public int ID { get; set; }
        [Display(Name="Nome")]
        [Required(ErrorMessage="O campo nome do layout é obrigatório!")]
        public string NOME { get; set; }
        [Display(Name = "Descrição")]
        public string DESCRICAO { get; set; }
        [Display(Name = "Arquivo")]
        [Range(1, int.MaxValue, ErrorMessage = "O arquivo do layout é obrigatório!")]
        public int ID_ARQUIVO { get; set; }
    
        public virtual ARQUIVO ARQUIVO { get; set; }
        public virtual ICollection<ARQUIVODETALHE> ARQUIVODETALHE { get; set; }
    }
}
