//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAYOUTDETALHE
    {
        public int ID { get; set; }
        public int ID_LAYOUT { get; set; }
        public int TAMANHO { get; set; }
        public int INICIO { get; set; }
        public int FIM { get; set; }
        public int ID_TIPO { get; set; }
        public Nullable<int> ID_VALIDACAO { get; set; }
        public Nullable<int> ID_LISTA { get; set; }
        public string ACEITAVEL { get; set; }
        public string FIXO { get; set; }
        public string NOME { get; set; }
        public int ID_HIERARQUIA { get; set; }
        public bool OBRIGATORIO { get; set; }
    
        public virtual HIERARQUIA HIERARQUIA { get; set; }
        public virtual TIPO TIPO { get; set; }
        public virtual LISTA LISTA { get; set; }
        public virtual VALIDACAO VALIDACAO { get; set; }
    }
}
