//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class LAYOUTDETALHE
    {
        public int ID { get; set; }
        public int ID_LAYOUT { get; set; }
        public int TAMANHO { get; set; }
        public int INICIO { get; set; }
        public int FIM { get; set; }
        public int ID_TIPO { get; set; }
        public Nullable<int> ID_VALIDACAO { get; set; }
        public Nullable<int> ID_LISTA { get; set; }
        public string ACEITAVEL { get; set; }
        public string FIXO { get; set; }
        public string NOME { get; set; }
        public bool OBRIGATORIO { get; set; }
        public Nullable<int> ORDEM { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual LAYOUT LAYOUT { get; set; }
        public virtual LISTA LISTA { get; set; }
        public virtual TIPO TIPO { get; set; }
        public virtual VALIDACAO VALIDACAO { get; set; }
    }

    [MetadataType(typeof(LayoutDetalheMetaData))]
    public partial class LAYOUTDETALHE
    { }

    public class LayoutDetalheMetaData
    {
        public int ID { get; set; }
        [Display(Name="Layout")]
        [Range(1,Int32.MaxValue, ErrorMessage="O campo layout é obrigatório!")]
        public int ID_LAYOUT { get; set; }
        [Display(Name = "Tamanho")]
        [Range(1, Int32.MaxValue, ErrorMessage = "O campo tamanho é obrigatório!")]
        public int TAMANHO { get; set; }
        [Display(Name = "Inicio")]
        public int INICIO { get; set; }
        [Display(Name = "Fim")]
        public int FIM { get; set; }
        [Display(Name = "Tipo")]
        [Range(1, Int32.MaxValue, ErrorMessage = "O campo tipo é obrigatório!")]
        public int ID_TIPO { get; set; }
        [Display(Name = "Validação")]
        public Nullable<int> ID_VALIDACAO { get; set; }
        [Display(Name = "Lista")]
        public Nullable<int> ID_LISTA { get; set; }
        [Display(Name = "Aceitável")]
        [StringLength(50)]
        public string ACEITAVEL { get; set; }
        [Display(Name = "Fixo")]
        [Required(ErrorMessage="O campo fixo é obrigatório!")]
        [StringLength(50)]
        public string FIXO { get; set; }
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "O campo nome é obrigatório!")]
        [StringLength(50)]
        public string NOME { get; set; }
        [Display(Name = "Obrigatório?")]
        public bool OBRIGATORIO { get; set; }
        [Display(Name = "Ordem")]
        [Range(1, Int32.MaxValue, ErrorMessage = "O campo ordem é obrigatório!")]
        public Nullable<int> ORDEM { get; set; }
        [Display(Name = "Descrição")]
        [StringLength(200)]
        public string DESCRICAO { get; set; }

        public virtual LAYOUT LAYOUT { get; set; }
        public virtual LISTA LISTA { get; set; }
        public virtual TIPO TIPO { get; set; }
        public virtual VALIDACAO VALIDACAO { get; set; }
    }
}
