//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTADETALHE
    {
        public int ID { get; set; }
        public string VALOR { get; set; }
        public int ID_LISTA { get; set; }
    
        public virtual LISTA LISTA { get; set; }
    }
}
