//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LISTADETALHE
    {
        public int ID { get; set; }
        public string VALOR { get; set; }
        public int ID_LISTA { get; set; }
    
        public virtual LISTA LISTA { get; set; }
    }
    [MetadataType(typeof(ListaDetalheMetaData))]
    public partial class LISTADETALHE
    { }
    public class ListaDetalheMetaData
    {
        public int ID { get; set; }
        [Display(Name="Valor")]
        [Required(ErrorMessage="O campo valor é obrigatório!")]
        [StringLength(200)]
        public string VALOR { get; set; }
        [Display(Name = "Lista")]
        [Range(1,Int32.MaxValue, ErrorMessage="O campo lista é obrigatório!")]
        public int ID_LISTA { get; set; }

        public virtual LISTA LISTA { get; set; }
    }
}
