//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAffinitiesMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TIPO
    {
        public TIPO()
        {
            this.LAYOUTDETALHE = new HashSet<LAYOUTDETALHE>();
        }
    
        public int ID { get; set; }
        [Display(Name="Tipo")]
        public string NOME { get; set; }
    
        public virtual ICollection<LAYOUTDETALHE> LAYOUTDETALHE { get; set; }
    }
}
